// <auto-generated />
using System;
using BikeRentalPoint.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeRentalPoint.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(BikeRentalPointDbContext))]
    [Migration("20251224103425_UpdateBikeRentalModel")]
    partial class UpdateBikeRentalModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Bike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("color");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("char(36)")
                        .HasColumnName("model_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("serial_number");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("bike", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7ea642e-c7d8-4a66-9660-757e1d55e1f2"),
                            Color = "Red",
                            ModelId = new Guid("6a9c0efe-2bc0-4e64-9c4f-fdc9fff23108"),
                            SerialNumber = "101"
                        },
                        new
                        {
                            Id = new Guid("80cf1be0-4bd7-40b2-9e48-b86cb56fff12"),
                            Color = "Blue",
                            ModelId = new Guid("671e5425-28a2-4d9f-bc07-5dd81f8f3c64"),
                            SerialNumber = "102"
                        },
                        new
                        {
                            Id = new Guid("160e4ff6-8a73-4df8-be70-a97a5428ee83"),
                            Color = "Black",
                            ModelId = new Guid("b5b6735d-45fa-4c62-b653-db81f7121d84"),
                            SerialNumber = "103"
                        },
                        new
                        {
                            Id = new Guid("2cc7ef72-0a74-4cdd-83a9-c3e163f0dd70"),
                            Color = "Green",
                            ModelId = new Guid("4d46e705-4b64-40d3-8883-f12934993abc"),
                            SerialNumber = "104"
                        },
                        new
                        {
                            Id = new Guid("b6ce7e19-cd47-4fd6-a531-c48e5809d555"),
                            Color = "White",
                            ModelId = new Guid("8dea56e8-6982-4339-8a8b-5b08b43e36be"),
                            SerialNumber = "105"
                        },
                        new
                        {
                            Id = new Guid("aad23158-ce0b-41ac-836b-a66c0a57ce30"),
                            Color = "Yellow",
                            ModelId = new Guid("e45334d8-7bd4-4d04-ba7a-9a382185c4f9"),
                            SerialNumber = "106"
                        },
                        new
                        {
                            Id = new Guid("4948faf4-935b-4d9a-800a-4e2816760d68"),
                            Color = "Silver",
                            ModelId = new Guid("e2ad9828-414d-409e-b3e1-344ff44b19c1"),
                            SerialNumber = "107"
                        },
                        new
                        {
                            Id = new Guid("d546a410-ebd2-49cc-a6cf-e9e0eb3c3daa"),
                            Color = "Gray",
                            ModelId = new Guid("e7c23725-116a-4e40-a1cc-660a5373d188"),
                            SerialNumber = "108"
                        },
                        new
                        {
                            Id = new Guid("dfecdb38-11f8-4d75-ba9c-35787ff76810"),
                            Color = "Orange",
                            ModelId = new Guid("b8061bf4-0826-43e6-9cbc-41ee8452d755"),
                            SerialNumber = "109"
                        },
                        new
                        {
                            Id = new Guid("8cdfc712-b2b0-451a-8196-358529d251ac"),
                            Color = "Purple",
                            ModelId = new Guid("2b22dd33-eccf-4f04-a52c-4ac4df78720b"),
                            SerialNumber = "110"
                        });
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("BikeType")
                        .HasColumnType("int")
                        .HasColumnName("bike_type");

                    b.Property<double?>("BikeWeight")
                        .HasColumnType("double")
                        .HasColumnName("bike_weight");

                    b.Property<int>("BrakeType")
                        .HasColumnType("int")
                        .HasColumnName("brake_type");

                    b.Property<double?>("MaxPassengerWeight")
                        .HasColumnType("double")
                        .HasColumnName("max_passenger_weight");

                    b.Property<int?>("ModelYear")
                        .HasColumnType("int")
                        .HasColumnName("model_year");

                    b.Property<decimal>("PricePerHour")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_per_hour");

                    b.Property<double?>("WheelSize")
                        .HasColumnType("double")
                        .HasColumnName("wheel_size");

                    b.HasKey("Id");

                    b.ToTable("model", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a9c0efe-2bc0-4e64-9c4f-fdc9fff23108"),
                            BikeType = 0,
                            BikeWeight = 9.0,
                            BrakeType = 1,
                            MaxPassengerWeight = 100.0,
                            ModelYear = 2022,
                            PricePerHour = 12m,
                            WheelSize = 28.0
                        },
                        new
                        {
                            Id = new Guid("671e5425-28a2-4d9f-bc07-5dd81f8f3c64"),
                            BikeType = 1,
                            BikeWeight = 11.0,
                            BrakeType = 0,
                            MaxPassengerWeight = 110.0,
                            ModelYear = 2021,
                            PricePerHour = 10m,
                            WheelSize = 26.0
                        },
                        new
                        {
                            Id = new Guid("b5b6735d-45fa-4c62-b653-db81f7121d84"),
                            BikeType = 1,
                            BikeWeight = 13.0,
                            BrakeType = 1,
                            MaxPassengerWeight = 120.0,
                            ModelYear = 2023,
                            PricePerHour = 15m,
                            WheelSize = 29.0
                        },
                        new
                        {
                            Id = new Guid("4d46e705-4b64-40d3-8883-f12934993abc"),
                            BikeType = 2,
                            BikeWeight = 10.0,
                            BrakeType = 0,
                            MaxPassengerWeight = 90.0,
                            ModelYear = 2020,
                            PricePerHour = 9m,
                            WheelSize = 27.5
                        },
                        new
                        {
                            Id = new Guid("8dea56e8-6982-4339-8a8b-5b08b43e36be"),
                            BikeType = 0,
                            BikeWeight = 12.0,
                            BrakeType = 2,
                            MaxPassengerWeight = 100.0,
                            ModelYear = 2024,
                            PricePerHour = 14m,
                            WheelSize = 28.0
                        },
                        new
                        {
                            Id = new Guid("e45334d8-7bd4-4d04-ba7a-9a382185c4f9"),
                            BikeType = 4,
                            BikeWeight = 8.0,
                            BrakeType = 3,
                            MaxPassengerWeight = 80.0,
                            ModelYear = 2019,
                            PricePerHour = 8m,
                            WheelSize = 24.0
                        },
                        new
                        {
                            Id = new Guid("e2ad9828-414d-409e-b3e1-344ff44b19c1"),
                            BikeType = 3,
                            BikeWeight = 14.0,
                            BrakeType = 1,
                            MaxPassengerWeight = 100.0,
                            ModelYear = 2024,
                            PricePerHour = 16m,
                            WheelSize = 26.0
                        },
                        new
                        {
                            Id = new Guid("e7c23725-116a-4e40-a1cc-660a5373d188"),
                            BikeType = 1,
                            BikeWeight = 15.0,
                            BrakeType = 5,
                            MaxPassengerWeight = 130.0,
                            ModelYear = 2023,
                            PricePerHour = 13m,
                            WheelSize = 29.0
                        },
                        new
                        {
                            Id = new Guid("b8061bf4-0826-43e6-9cbc-41ee8452d755"),
                            BikeType = 2,
                            BikeWeight = 11.0,
                            BrakeType = 0,
                            MaxPassengerWeight = 95.0,
                            ModelYear = 2021,
                            PricePerHour = 11m,
                            WheelSize = 27.0
                        },
                        new
                        {
                            Id = new Guid("2b22dd33-eccf-4f04-a52c-4ac4df78720b"),
                            BikeType = 0,
                            BikeWeight = 12.0,
                            BrakeType = 1,
                            MaxPassengerWeight = 120.0,
                            ModelYear = 2025,
                            PricePerHour = 17m,
                            WheelSize = 28.0
                        });
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Rent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("BikeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("bike_id");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)")
                        .HasColumnName("duration");

                    b.Property<Guid>("RenterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("renter_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("RenterId");

                    b.ToTable("rent", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("080e7d48-2167-4bcd-9123-1dbbf2a8f1af"),
                            BikeId = new Guid("f7ea642e-c7d8-4a66-9660-757e1d55e1f2"),
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = new Guid("e3803c2c-1d4f-4a94-b6e8-43418b11cf3d"),
                            StartTime = new DateTime(2025, 12, 22, 12, 34, 24, 298, DateTimeKind.Local).AddTicks(5363)
                        },
                        new
                        {
                            Id = new Guid("f47719be-6652-488c-ac6a-b90c2da6f02a"),
                            BikeId = new Guid("80cf1be0-4bd7-40b2-9e48-b86cb56fff12"),
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            RenterId = new Guid("aea707e2-152c-44b3-b40b-e46a0a9d0047"),
                            StartTime = new DateTime(2025, 12, 22, 22, 34, 24, 298, DateTimeKind.Local).AddTicks(6288)
                        },
                        new
                        {
                            Id = new Guid("fd52bef8-dbe2-43b5-b8e5-bb688c60903c"),
                            BikeId = new Guid("160e4ff6-8a73-4df8-be70-a97a5428ee83"),
                            Duration = new TimeSpan(0, 4, 0, 0, 0),
                            RenterId = new Guid("8275540f-31af-4291-b809-373d9291c5e0"),
                            StartTime = new DateTime(2025, 12, 23, 8, 34, 24, 298, DateTimeKind.Local).AddTicks(6297)
                        },
                        new
                        {
                            Id = new Guid("4de3abf1-efc7-4a16-b34d-70375969fc3a"),
                            BikeId = new Guid("2cc7ef72-0a74-4cdd-83a9-c3e163f0dd70"),
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            RenterId = new Guid("4eec356c-e16c-4f83-b01a-acb228d09e35"),
                            StartTime = new DateTime(2025, 12, 23, 18, 34, 24, 298, DateTimeKind.Local).AddTicks(6300)
                        },
                        new
                        {
                            Id = new Guid("31777f35-0c75-4f73-b06e-282d822c1392"),
                            BikeId = new Guid("b6ce7e19-cd47-4fd6-a531-c48e5809d555"),
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            RenterId = new Guid("e5b43429-1e08-44e1-ade2-5307812fa40f"),
                            StartTime = new DateTime(2025, 12, 24, 4, 34, 24, 298, DateTimeKind.Local).AddTicks(6306)
                        },
                        new
                        {
                            Id = new Guid("d7ec7795-9c7a-4814-8029-f1fa336f291a"),
                            BikeId = new Guid("aad23158-ce0b-41ac-836b-a66c0a57ce30"),
                            Duration = new TimeSpan(0, 5, 0, 0, 0),
                            RenterId = new Guid("a4029112-136c-4689-bfca-f8b64afc9b87"),
                            StartTime = new DateTime(2025, 12, 24, 9, 34, 24, 298, DateTimeKind.Local).AddTicks(6309)
                        },
                        new
                        {
                            Id = new Guid("a6e03ffb-f13c-452f-a818-83a411941a1b"),
                            BikeId = new Guid("4948faf4-935b-4d9a-800a-4e2816760d68"),
                            Duration = new TimeSpan(0, 6, 0, 0, 0),
                            RenterId = new Guid("ff8c419a-401a-46b9-a544-a3d9f81e96de"),
                            StartTime = new DateTime(2025, 12, 24, 11, 34, 24, 298, DateTimeKind.Local).AddTicks(6311)
                        },
                        new
                        {
                            Id = new Guid("db62ab99-6af9-4620-a96f-31c9e9d99344"),
                            BikeId = new Guid("d546a410-ebd2-49cc-a6cf-e9e0eb3c3daa"),
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            RenterId = new Guid("81ecca56-1aef-481c-a15b-a64f43e22df0"),
                            StartTime = new DateTime(2025, 12, 24, 12, 34, 24, 298, DateTimeKind.Local).AddTicks(6326)
                        },
                        new
                        {
                            Id = new Guid("d0176ef7-5c84-4c72-b91b-b2591f9457ab"),
                            BikeId = new Guid("dfecdb38-11f8-4d75-ba9c-35787ff76810"),
                            Duration = new TimeSpan(0, 3, 30, 0, 0),
                            RenterId = new Guid("4b45a861-d993-4f44-87c4-fac41fb6494b"),
                            StartTime = new DateTime(2025, 12, 24, 13, 34, 24, 298, DateTimeKind.Local).AddTicks(6329)
                        },
                        new
                        {
                            Id = new Guid("a037529b-b217-4f53-beea-172461c4ddc2"),
                            BikeId = new Guid("160e4ff6-8a73-4df8-be70-a97a5428ee83"),
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            RenterId = new Guid("e3803c2c-1d4f-4a94-b6e8-43418b11cf3d"),
                            StartTime = new DateTime(2025, 12, 23, 13, 34, 24, 298, DateTimeKind.Local).AddTicks(6332)
                        },
                        new
                        {
                            Id = new Guid("7c9937af-d8f8-4b61-8d95-40c8bd0f5488"),
                            BikeId = new Guid("4948faf4-935b-4d9a-800a-4e2816760d68"),
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = new Guid("aea707e2-152c-44b3-b40b-e46a0a9d0047"),
                            StartTime = new DateTime(2025, 12, 23, 23, 34, 24, 298, DateTimeKind.Local).AddTicks(6334)
                        },
                        new
                        {
                            Id = new Guid("fbc6af3c-701b-49cf-949f-41df984271cd"),
                            BikeId = new Guid("d546a410-ebd2-49cc-a6cf-e9e0eb3c3daa"),
                            Duration = new TimeSpan(0, 5, 0, 0, 0),
                            RenterId = new Guid("4eec356c-e16c-4f83-b01a-acb228d09e35"),
                            StartTime = new DateTime(2025, 12, 24, 2, 34, 24, 298, DateTimeKind.Local).AddTicks(6337)
                        },
                        new
                        {
                            Id = new Guid("c2f7bc0b-834d-4930-8b2b-57c9bd76e35a"),
                            BikeId = new Guid("b6ce7e19-cd47-4fd6-a531-c48e5809d555"),
                            Duration = new TimeSpan(0, 4, 0, 0, 0),
                            RenterId = new Guid("a4029112-136c-4689-bfca-f8b64afc9b87"),
                            StartTime = new DateTime(2025, 12, 24, 6, 34, 24, 298, DateTimeKind.Local).AddTicks(6341)
                        },
                        new
                        {
                            Id = new Guid("37a0baf3-cc36-4d2d-ac2c-209584154ccd"),
                            BikeId = new Guid("aad23158-ce0b-41ac-836b-a66c0a57ce30"),
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            RenterId = new Guid("81ecca56-1aef-481c-a15b-a64f43e22df0"),
                            StartTime = new DateTime(2025, 12, 24, 8, 34, 24, 298, DateTimeKind.Local).AddTicks(6344)
                        },
                        new
                        {
                            Id = new Guid("fe68990f-5ccf-4025-91bd-06958a0d5e83"),
                            BikeId = new Guid("2cc7ef72-0a74-4cdd-83a9-c3e163f0dd70"),
                            Duration = new TimeSpan(0, 3, 30, 0, 0),
                            RenterId = new Guid("4b45a861-d993-4f44-87c4-fac41fb6494b"),
                            StartTime = new DateTime(2025, 12, 24, 10, 34, 24, 298, DateTimeKind.Local).AddTicks(6347)
                        },
                        new
                        {
                            Id = new Guid("2aeb83b7-11b7-45de-927d-fa53ae799ec6"),
                            BikeId = new Guid("8cdfc712-b2b0-451a-8196-358529d251ac"),
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = new Guid("e3803c2c-1d4f-4a94-b6e8-43418b11cf3d"),
                            StartTime = new DateTime(2025, 12, 24, 13, 4, 24, 298, DateTimeKind.Local).AddTicks(6349)
                        },
                        new
                        {
                            Id = new Guid("5e7242b3-1798-4a69-b5c2-ce3ac97c132e"),
                            BikeId = new Guid("d546a410-ebd2-49cc-a6cf-e9e0eb3c3daa"),
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            RenterId = new Guid("8275540f-31af-4291-b809-373d9291c5e0"),
                            StartTime = new DateTime(2025, 12, 24, 14, 4, 24, 298, DateTimeKind.Local).AddTicks(6352)
                        },
                        new
                        {
                            Id = new Guid("86ea8960-4861-420f-a8b1-26fcff8ead54"),
                            BikeId = new Guid("aad23158-ce0b-41ac-836b-a66c0a57ce30"),
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = new Guid("e5b43429-1e08-44e1-ade2-5307812fa40f"),
                            StartTime = new DateTime(2025, 12, 24, 14, 22, 24, 298, DateTimeKind.Local).AddTicks(6354)
                        });
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Renter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("renter", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3803c2c-1d4f-4a94-b6e8-43418b11cf3d"),
                            LastName = "Иванов",
                            MiddleName = "Иванович",
                            Name = "Иван",
                            PhoneNumber = "111-111"
                        },
                        new
                        {
                            Id = new Guid("aea707e2-152c-44b3-b40b-e46a0a9d0047"),
                            LastName = "Петров",
                            MiddleName = "Петрович",
                            Name = "Петр",
                            PhoneNumber = "222-222"
                        },
                        new
                        {
                            Id = new Guid("8275540f-31af-4291-b809-373d9291c5e0"),
                            LastName = "Сидоров",
                            MiddleName = "Сидорович",
                            Name = "Сидор",
                            PhoneNumber = "333-333"
                        },
                        new
                        {
                            Id = new Guid("4eec356c-e16c-4f83-b01a-acb228d09e35"),
                            LastName = "Алексеев",
                            MiddleName = "Николаевич",
                            Name = "Алексей",
                            PhoneNumber = "444-444"
                        },
                        new
                        {
                            Id = new Guid("e5b43429-1e08-44e1-ade2-5307812fa40f"),
                            LastName = "Васильев",
                            MiddleName = "Павлович",
                            Name = "Василий",
                            PhoneNumber = "555-555"
                        },
                        new
                        {
                            Id = new Guid("a4029112-136c-4689-bfca-f8b64afc9b87"),
                            LastName = "Кузнецов",
                            MiddleName = "Игоревич",
                            Name = "Сергей",
                            PhoneNumber = "666-666"
                        },
                        new
                        {
                            Id = new Guid("ff8c419a-401a-46b9-a544-a3d9f81e96de"),
                            LastName = "Никитин",
                            MiddleName = "Андреевич",
                            Name = "Никита",
                            PhoneNumber = "777-777"
                        },
                        new
                        {
                            Id = new Guid("81ecca56-1aef-481c-a15b-a64f43e22df0"),
                            LastName = "Федоров",
                            MiddleName = "Владимирович",
                            Name = "Федор",
                            PhoneNumber = "888-888"
                        },
                        new
                        {
                            Id = new Guid("4b45a861-d993-4f44-87c4-fac41fb6494b"),
                            LastName = "Смирнов",
                            MiddleName = "Валерьевич",
                            Name = "Семен",
                            PhoneNumber = "999-999"
                        },
                        new
                        {
                            Id = new Guid("c2c0b965-9a05-49cb-8051-5ce6d26761af"),
                            LastName = "Попов",
                            MiddleName = "Алексеевич",
                            Name = "Дмитрий",
                            PhoneNumber = "000-000"
                        });
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Bike", b =>
                {
                    b.HasOne("BikeRentalPoint.Domain.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Rent", b =>
                {
                    b.HasOne("BikeRentalPoint.Domain.Models.Bike", "Bike")
                        .WithMany()
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BikeRentalPoint.Domain.Models.Renter", "Renter")
                        .WithMany()
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Renter");
                });
#pragma warning restore 612, 618
        }
    }
}
