// <auto-generated />
using System;
using BikeRentalPoint.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeRentalPoint.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(BikeRentalPointDbContext))]
    [Migration("20251224103822_SyncModelSnapshot")]
    partial class SyncModelSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Bike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("color");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("char(36)")
                        .HasColumnName("model_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("serial_number");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("bike", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7cbe88b3-efd6-43d3-abf3-ac8e8d9ea158"),
                            Color = "Red",
                            ModelId = new Guid("26af4f3e-a8ce-4780-ba61-11c1b02e8c8f"),
                            SerialNumber = "101"
                        },
                        new
                        {
                            Id = new Guid("610365e0-c878-4296-a66f-e901fb12bbaa"),
                            Color = "Blue",
                            ModelId = new Guid("01c16a54-51b0-4e1d-baa0-cbd9edfb1e68"),
                            SerialNumber = "102"
                        },
                        new
                        {
                            Id = new Guid("623f5102-30c6-4b97-a492-f6ad9bc6cd20"),
                            Color = "Black",
                            ModelId = new Guid("ab60dde3-c3b4-4424-98a5-523596d84e49"),
                            SerialNumber = "103"
                        },
                        new
                        {
                            Id = new Guid("ad3afcbe-6b97-4b96-8ba2-deaf5d2c53b5"),
                            Color = "Green",
                            ModelId = new Guid("29a4a967-f786-460b-aa3a-09fe77ebc4cd"),
                            SerialNumber = "104"
                        },
                        new
                        {
                            Id = new Guid("b60d7365-728c-4801-984b-45f47a23876d"),
                            Color = "White",
                            ModelId = new Guid("001e6fcd-5a65-4592-8475-598bae3421bc"),
                            SerialNumber = "105"
                        },
                        new
                        {
                            Id = new Guid("1d12d97a-593b-4a03-b151-d65bf8aa3a84"),
                            Color = "Yellow",
                            ModelId = new Guid("86571f83-df76-49d4-8066-3d778049c98d"),
                            SerialNumber = "106"
                        },
                        new
                        {
                            Id = new Guid("3d57e48d-c20b-4beb-bf0f-0050a490fa4c"),
                            Color = "Silver",
                            ModelId = new Guid("950a5ff4-beb7-42ae-9fe2-bc6a351fe380"),
                            SerialNumber = "107"
                        },
                        new
                        {
                            Id = new Guid("c39de33e-b0fe-4ec8-bb97-02dcd929528c"),
                            Color = "Gray",
                            ModelId = new Guid("223d4e89-84d2-4606-88db-5cbb6649dbfc"),
                            SerialNumber = "108"
                        },
                        new
                        {
                            Id = new Guid("6e872a9a-bacb-4d0d-baa0-b72af61a56a7"),
                            Color = "Orange",
                            ModelId = new Guid("ed8f35b4-7af5-4681-a8a7-b18d0227f3aa"),
                            SerialNumber = "109"
                        },
                        new
                        {
                            Id = new Guid("9a49bfd3-fe3b-43f5-a884-fb2136488f54"),
                            Color = "Purple",
                            ModelId = new Guid("57454149-3d5f-46f7-ad67-59c9c20e4b8a"),
                            SerialNumber = "110"
                        });
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("BikeType")
                        .HasColumnType("int")
                        .HasColumnName("bike_type");

                    b.Property<double?>("BikeWeight")
                        .HasColumnType("double")
                        .HasColumnName("bike_weight");

                    b.Property<int>("BrakeType")
                        .HasColumnType("int")
                        .HasColumnName("brake_type");

                    b.Property<double?>("MaxPassengerWeight")
                        .HasColumnType("double")
                        .HasColumnName("max_passenger_weight");

                    b.Property<int?>("ModelYear")
                        .HasColumnType("int")
                        .HasColumnName("model_year");

                    b.Property<decimal>("PricePerHour")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_per_hour");

                    b.Property<double?>("WheelSize")
                        .HasColumnType("double")
                        .HasColumnName("wheel_size");

                    b.HasKey("Id");

                    b.ToTable("model", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("26af4f3e-a8ce-4780-ba61-11c1b02e8c8f"),
                            BikeType = 0,
                            BikeWeight = 9.0,
                            BrakeType = 1,
                            MaxPassengerWeight = 100.0,
                            ModelYear = 2022,
                            PricePerHour = 12m,
                            WheelSize = 28.0
                        },
                        new
                        {
                            Id = new Guid("01c16a54-51b0-4e1d-baa0-cbd9edfb1e68"),
                            BikeType = 1,
                            BikeWeight = 11.0,
                            BrakeType = 0,
                            MaxPassengerWeight = 110.0,
                            ModelYear = 2021,
                            PricePerHour = 10m,
                            WheelSize = 26.0
                        },
                        new
                        {
                            Id = new Guid("ab60dde3-c3b4-4424-98a5-523596d84e49"),
                            BikeType = 1,
                            BikeWeight = 13.0,
                            BrakeType = 1,
                            MaxPassengerWeight = 120.0,
                            ModelYear = 2023,
                            PricePerHour = 15m,
                            WheelSize = 29.0
                        },
                        new
                        {
                            Id = new Guid("29a4a967-f786-460b-aa3a-09fe77ebc4cd"),
                            BikeType = 2,
                            BikeWeight = 10.0,
                            BrakeType = 0,
                            MaxPassengerWeight = 90.0,
                            ModelYear = 2020,
                            PricePerHour = 9m,
                            WheelSize = 27.5
                        },
                        new
                        {
                            Id = new Guid("001e6fcd-5a65-4592-8475-598bae3421bc"),
                            BikeType = 0,
                            BikeWeight = 12.0,
                            BrakeType = 2,
                            MaxPassengerWeight = 100.0,
                            ModelYear = 2024,
                            PricePerHour = 14m,
                            WheelSize = 28.0
                        },
                        new
                        {
                            Id = new Guid("86571f83-df76-49d4-8066-3d778049c98d"),
                            BikeType = 4,
                            BikeWeight = 8.0,
                            BrakeType = 3,
                            MaxPassengerWeight = 80.0,
                            ModelYear = 2019,
                            PricePerHour = 8m,
                            WheelSize = 24.0
                        },
                        new
                        {
                            Id = new Guid("950a5ff4-beb7-42ae-9fe2-bc6a351fe380"),
                            BikeType = 3,
                            BikeWeight = 14.0,
                            BrakeType = 1,
                            MaxPassengerWeight = 100.0,
                            ModelYear = 2024,
                            PricePerHour = 16m,
                            WheelSize = 26.0
                        },
                        new
                        {
                            Id = new Guid("223d4e89-84d2-4606-88db-5cbb6649dbfc"),
                            BikeType = 1,
                            BikeWeight = 15.0,
                            BrakeType = 5,
                            MaxPassengerWeight = 130.0,
                            ModelYear = 2023,
                            PricePerHour = 13m,
                            WheelSize = 29.0
                        },
                        new
                        {
                            Id = new Guid("ed8f35b4-7af5-4681-a8a7-b18d0227f3aa"),
                            BikeType = 2,
                            BikeWeight = 11.0,
                            BrakeType = 0,
                            MaxPassengerWeight = 95.0,
                            ModelYear = 2021,
                            PricePerHour = 11m,
                            WheelSize = 27.0
                        },
                        new
                        {
                            Id = new Guid("57454149-3d5f-46f7-ad67-59c9c20e4b8a"),
                            BikeType = 0,
                            BikeWeight = 12.0,
                            BrakeType = 1,
                            MaxPassengerWeight = 120.0,
                            ModelYear = 2025,
                            PricePerHour = 17m,
                            WheelSize = 28.0
                        });
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Rent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("BikeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("bike_id");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)")
                        .HasColumnName("duration");

                    b.Property<Guid>("RenterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("renter_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("RenterId");

                    b.ToTable("rent", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("db9a469b-7715-4d1d-9381-69c23a954c5f"),
                            BikeId = new Guid("7cbe88b3-efd6-43d3-abf3-ac8e8d9ea158"),
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = new Guid("bbc8ef69-6b1a-4d19-bf96-72dbf6a3b86d"),
                            StartTime = new DateTime(2025, 12, 22, 12, 38, 21, 354, DateTimeKind.Local).AddTicks(763)
                        },
                        new
                        {
                            Id = new Guid("a3ce076e-bec2-4329-95d3-5b6b8fb3fe92"),
                            BikeId = new Guid("610365e0-c878-4296-a66f-e901fb12bbaa"),
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            RenterId = new Guid("743960e3-0371-47c8-80f5-c62f461decaf"),
                            StartTime = new DateTime(2025, 12, 22, 22, 38, 21, 354, DateTimeKind.Local).AddTicks(1652)
                        },
                        new
                        {
                            Id = new Guid("c380d0db-8558-4f2f-83a6-ae01b2425f15"),
                            BikeId = new Guid("623f5102-30c6-4b97-a492-f6ad9bc6cd20"),
                            Duration = new TimeSpan(0, 4, 0, 0, 0),
                            RenterId = new Guid("0841a662-5040-447a-8691-bc4e7f3368a4"),
                            StartTime = new DateTime(2025, 12, 23, 8, 38, 21, 354, DateTimeKind.Local).AddTicks(1659)
                        },
                        new
                        {
                            Id = new Guid("2414c2de-fd19-4d38-a4ca-45d664cf71ce"),
                            BikeId = new Guid("ad3afcbe-6b97-4b96-8ba2-deaf5d2c53b5"),
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            RenterId = new Guid("027ed055-e56d-489d-9c3f-7f842632c3f7"),
                            StartTime = new DateTime(2025, 12, 23, 18, 38, 21, 354, DateTimeKind.Local).AddTicks(1664)
                        },
                        new
                        {
                            Id = new Guid("fc380d30-e92d-4178-8f32-b9f3466529a5"),
                            BikeId = new Guid("b60d7365-728c-4801-984b-45f47a23876d"),
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            RenterId = new Guid("a46b03d5-195b-4dfd-9958-a89d1c4094d2"),
                            StartTime = new DateTime(2025, 12, 24, 4, 38, 21, 354, DateTimeKind.Local).AddTicks(1667)
                        },
                        new
                        {
                            Id = new Guid("d0e5f183-638a-45a0-8c9f-05761b6d7558"),
                            BikeId = new Guid("1d12d97a-593b-4a03-b151-d65bf8aa3a84"),
                            Duration = new TimeSpan(0, 5, 0, 0, 0),
                            RenterId = new Guid("714ac5c6-ba03-4139-9800-10fb23d2c067"),
                            StartTime = new DateTime(2025, 12, 24, 9, 38, 21, 354, DateTimeKind.Local).AddTicks(1670)
                        },
                        new
                        {
                            Id = new Guid("cea82580-1108-4416-bcf9-8dc19b749cf5"),
                            BikeId = new Guid("3d57e48d-c20b-4beb-bf0f-0050a490fa4c"),
                            Duration = new TimeSpan(0, 6, 0, 0, 0),
                            RenterId = new Guid("72da748d-2127-42ce-8171-9343bb8e2658"),
                            StartTime = new DateTime(2025, 12, 24, 11, 38, 21, 354, DateTimeKind.Local).AddTicks(1673)
                        },
                        new
                        {
                            Id = new Guid("a23dfdd1-45c2-4191-b768-9f5d5f869929"),
                            BikeId = new Guid("c39de33e-b0fe-4ec8-bb97-02dcd929528c"),
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            RenterId = new Guid("c6d08001-9232-471e-a82e-f5da8f461ce6"),
                            StartTime = new DateTime(2025, 12, 24, 12, 38, 21, 354, DateTimeKind.Local).AddTicks(1675)
                        },
                        new
                        {
                            Id = new Guid("56951888-d020-41bb-929a-88020ac64842"),
                            BikeId = new Guid("6e872a9a-bacb-4d0d-baa0-b72af61a56a7"),
                            Duration = new TimeSpan(0, 3, 30, 0, 0),
                            RenterId = new Guid("ba0fade0-8861-4f6f-b308-238883bb2909"),
                            StartTime = new DateTime(2025, 12, 24, 13, 38, 21, 354, DateTimeKind.Local).AddTicks(1678)
                        },
                        new
                        {
                            Id = new Guid("7e0cfe15-d60c-4eb2-94b8-2234266d6331"),
                            BikeId = new Guid("623f5102-30c6-4b97-a492-f6ad9bc6cd20"),
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            RenterId = new Guid("bbc8ef69-6b1a-4d19-bf96-72dbf6a3b86d"),
                            StartTime = new DateTime(2025, 12, 23, 13, 38, 21, 354, DateTimeKind.Local).AddTicks(1683)
                        },
                        new
                        {
                            Id = new Guid("b9771db7-09ce-426b-8b10-ab23548f46b8"),
                            BikeId = new Guid("3d57e48d-c20b-4beb-bf0f-0050a490fa4c"),
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = new Guid("743960e3-0371-47c8-80f5-c62f461decaf"),
                            StartTime = new DateTime(2025, 12, 23, 23, 38, 21, 354, DateTimeKind.Local).AddTicks(1685)
                        },
                        new
                        {
                            Id = new Guid("12a23d94-4b4f-4bec-9d7c-86093a2eec78"),
                            BikeId = new Guid("c39de33e-b0fe-4ec8-bb97-02dcd929528c"),
                            Duration = new TimeSpan(0, 5, 0, 0, 0),
                            RenterId = new Guid("027ed055-e56d-489d-9c3f-7f842632c3f7"),
                            StartTime = new DateTime(2025, 12, 24, 2, 38, 21, 354, DateTimeKind.Local).AddTicks(1688)
                        },
                        new
                        {
                            Id = new Guid("dfae4011-d364-419b-991d-5c39facfd611"),
                            BikeId = new Guid("b60d7365-728c-4801-984b-45f47a23876d"),
                            Duration = new TimeSpan(0, 4, 0, 0, 0),
                            RenterId = new Guid("714ac5c6-ba03-4139-9800-10fb23d2c067"),
                            StartTime = new DateTime(2025, 12, 24, 6, 38, 21, 354, DateTimeKind.Local).AddTicks(1691)
                        },
                        new
                        {
                            Id = new Guid("4990a0d6-9b8c-431f-814b-c7da104fd90e"),
                            BikeId = new Guid("1d12d97a-593b-4a03-b151-d65bf8aa3a84"),
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            RenterId = new Guid("c6d08001-9232-471e-a82e-f5da8f461ce6"),
                            StartTime = new DateTime(2025, 12, 24, 8, 38, 21, 354, DateTimeKind.Local).AddTicks(1694)
                        },
                        new
                        {
                            Id = new Guid("eb21a9f9-14cd-41b4-b668-4682ca1dba75"),
                            BikeId = new Guid("ad3afcbe-6b97-4b96-8ba2-deaf5d2c53b5"),
                            Duration = new TimeSpan(0, 3, 30, 0, 0),
                            RenterId = new Guid("ba0fade0-8861-4f6f-b308-238883bb2909"),
                            StartTime = new DateTime(2025, 12, 24, 10, 38, 21, 354, DateTimeKind.Local).AddTicks(1697)
                        },
                        new
                        {
                            Id = new Guid("03dad402-2417-4efc-976c-59e0150beae2"),
                            BikeId = new Guid("9a49bfd3-fe3b-43f5-a884-fb2136488f54"),
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = new Guid("bbc8ef69-6b1a-4d19-bf96-72dbf6a3b86d"),
                            StartTime = new DateTime(2025, 12, 24, 13, 8, 21, 354, DateTimeKind.Local).AddTicks(1699)
                        },
                        new
                        {
                            Id = new Guid("addd5449-33e9-4e1b-80b6-47e1457e6164"),
                            BikeId = new Guid("c39de33e-b0fe-4ec8-bb97-02dcd929528c"),
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            RenterId = new Guid("0841a662-5040-447a-8691-bc4e7f3368a4"),
                            StartTime = new DateTime(2025, 12, 24, 14, 8, 21, 354, DateTimeKind.Local).AddTicks(1702)
                        },
                        new
                        {
                            Id = new Guid("0989bc71-2c42-4cfd-bcaa-b95ab9c1c195"),
                            BikeId = new Guid("1d12d97a-593b-4a03-b151-d65bf8aa3a84"),
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = new Guid("a46b03d5-195b-4dfd-9958-a89d1c4094d2"),
                            StartTime = new DateTime(2025, 12, 24, 14, 26, 21, 354, DateTimeKind.Local).AddTicks(1706)
                        });
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Renter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("renter", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbc8ef69-6b1a-4d19-bf96-72dbf6a3b86d"),
                            LastName = "Иванов",
                            MiddleName = "Иванович",
                            Name = "Иван",
                            PhoneNumber = "111-111"
                        },
                        new
                        {
                            Id = new Guid("743960e3-0371-47c8-80f5-c62f461decaf"),
                            LastName = "Петров",
                            MiddleName = "Петрович",
                            Name = "Петр",
                            PhoneNumber = "222-222"
                        },
                        new
                        {
                            Id = new Guid("0841a662-5040-447a-8691-bc4e7f3368a4"),
                            LastName = "Сидоров",
                            MiddleName = "Сидорович",
                            Name = "Сидор",
                            PhoneNumber = "333-333"
                        },
                        new
                        {
                            Id = new Guid("027ed055-e56d-489d-9c3f-7f842632c3f7"),
                            LastName = "Алексеев",
                            MiddleName = "Николаевич",
                            Name = "Алексей",
                            PhoneNumber = "444-444"
                        },
                        new
                        {
                            Id = new Guid("a46b03d5-195b-4dfd-9958-a89d1c4094d2"),
                            LastName = "Васильев",
                            MiddleName = "Павлович",
                            Name = "Василий",
                            PhoneNumber = "555-555"
                        },
                        new
                        {
                            Id = new Guid("714ac5c6-ba03-4139-9800-10fb23d2c067"),
                            LastName = "Кузнецов",
                            MiddleName = "Игоревич",
                            Name = "Сергей",
                            PhoneNumber = "666-666"
                        },
                        new
                        {
                            Id = new Guid("72da748d-2127-42ce-8171-9343bb8e2658"),
                            LastName = "Никитин",
                            MiddleName = "Андреевич",
                            Name = "Никита",
                            PhoneNumber = "777-777"
                        },
                        new
                        {
                            Id = new Guid("c6d08001-9232-471e-a82e-f5da8f461ce6"),
                            LastName = "Федоров",
                            MiddleName = "Владимирович",
                            Name = "Федор",
                            PhoneNumber = "888-888"
                        },
                        new
                        {
                            Id = new Guid("ba0fade0-8861-4f6f-b308-238883bb2909"),
                            LastName = "Смирнов",
                            MiddleName = "Валерьевич",
                            Name = "Семен",
                            PhoneNumber = "999-999"
                        },
                        new
                        {
                            Id = new Guid("c3ace681-d7cc-4f78-8986-17177396f976"),
                            LastName = "Попов",
                            MiddleName = "Алексеевич",
                            Name = "Дмитрий",
                            PhoneNumber = "000-000"
                        });
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Bike", b =>
                {
                    b.HasOne("BikeRentalPoint.Domain.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Rent", b =>
                {
                    b.HasOne("BikeRentalPoint.Domain.Models.Bike", "Bike")
                        .WithMany()
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BikeRentalPoint.Domain.Models.Renter", "Renter")
                        .WithMany()
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Renter");
                });
#pragma warning restore 612, 618
        }
    }
}
