using AutoMapper;
using Grpc.Core;
using BikeRentalPoint.Domain;
using BikeRentalPoint.Domain.Models;
using BikeRentalPoint.Grpc.Contracts;

namespace BikeRentalPoint.Api.Host.Grpc;

/// <summary>
/// Consumes data generated by the gRPC service and persists it to the database using EF Core repositories.
/// </summary>
public class GrpcClientConsumer(
    IRepository<Model, Guid> modelRepo,
    IRepository<Bike, Guid> bikeRepo,
    IRepository<Renter, Guid> renterRepo,
    IRepository<Rent, Guid> rentRepo,
    GenerationService.GenerationServiceClient grpcClient,
    IMapper mapper,
    ILogger<GrpcClientConsumer> logger)
{
    private readonly IRepository<Model, Guid> _modelRepo = modelRepo;
    private readonly IRepository<Bike, Guid> _bikeRepo = bikeRepo;
    private readonly IRepository<Renter, Guid> _renterRepo = renterRepo;
    private readonly IRepository<Rent, Guid> _rentRepo = rentRepo;
    private readonly GenerationService.GenerationServiceClient _grpcClient = grpcClient;
    private readonly IMapper _mapper = mapper;
    private readonly ILogger<GrpcClientConsumer> _logger = logger;

    /// <summary>
    /// Starts generation on the gRPC server and, while batches are streamed back,
    /// maps them to domain entities and saves them to the database.
    /// </summary>
    public async Task StartGenerationAsync(int totalCount, int batchSize, CancellationToken cancellationToken = default)
    {
        _logger.LogInformation(
            "Starting gRPC generation: TotalCount={TotalCount}, BatchSize={BatchSize}",
            totalCount,
            batchSize);

        try
        {
            using var call = _grpcClient.Generate(cancellationToken: cancellationToken);

            // отправляем только одно стартовое сообщение
            await call.RequestStream.WriteAsync(new GenerationRequest
            {
                Start = new StartGeneration
                {
                    TotalCount = totalCount,
                    BatchSize = batchSize
                }
            }, cancellationToken);

            // больше в RequestStream ничего не пишем
            await call.RequestStream.CompleteAsync();

            await foreach (var response in call.ResponseStream.ReadAllAsync(cancellationToken))
            {
                switch (response.PayloadCase)
                {
                    case GenerationResponse.PayloadOneofCase.Batch:
                        var batch = response.Batch;
                        _logger.LogInformation(
                            "Processing batch {BatchNumber}: Models={Models}, Bikes={Bikes}, Renters={Renters}, Rents={Rents}",
                            batch.BatchNumber,
                            batch.Models.Count,
                            batch.Bikes.Count,
                            batch.Renters.Count,
                            batch.Rents.Count);

                        foreach (var modelGrpc in batch.Models)
                        {
                            var model = _mapper.Map<Model>(modelGrpc);
                            await _modelRepo.Create(model);
                        }

                        foreach (var bikeGrpc in batch.Bikes)
                        {
                            var bike = _mapper.Map<Bike>(bikeGrpc);
                            await _bikeRepo.Create(bike);
                        }

                        foreach (var renterGrpc in batch.Renters)
                        {
                            var renter = _mapper.Map<Renter>(renterGrpc);
                            await _renterRepo.Create(renter);
                        }

                        foreach (var rentGrpc in batch.Rents)
                        {
                            var rent = _mapper.Map<Rent>(rentGrpc);
                            await _rentRepo.Create(rent);
                        }

                        break;

                    case GenerationResponse.PayloadOneofCase.Completed:
                        _logger.LogInformation(
                            "Generation completed. Total batches: {TotalBatches}",
                            response.Completed.TotalBatches);
                        break;

                    case GenerationResponse.PayloadOneofCase.Error:
                        _logger.LogError(
                            "Generation error from gRPC service: {Message}",
                            response.Error.Message);
                        break;
                }
            }
        }
        catch (RpcException ex) when (ex.StatusCode == StatusCode.Cancelled)
        {
            _logger.LogWarning(ex, "gRPC generation was cancelled by client.");
        }
        catch (RpcException ex)
        {
            _logger.LogError(ex, "gRPC error during generation: {Status} {Detail}", ex.StatusCode, ex.Status.Detail);
            throw;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Unexpected error while consuming gRPC generation stream.");
            throw;
        }
    }
}
